Feature/SNEK-14: Adds a control text to the bottom of the gameboard view. Adds a static StateManager class which manages the switch to different scenes and the GameBoard.
sorinlzr/snake pull request #17
Opened 2023-01-07 15:21 UTC by benniii1

2023-01-07 20:48 UTC, sorinlzr commented on src/main/java/at/ac/fhcampuswien/snake/controller/GameboardViewController.java
> +        this.gameBoard.setHeight(SCREEN_SIZE_MEDIUM - 50);
Can you create a constant instead of the magic value please, just to have it more clear what that represents?

Also can you please check if the collisions with the border walls still work after this change?

2023-01-07 20:48 UTC, sorinlzr commented on src/main/java/at/ac/fhcampuswien/snake/GameBoard.java
> +                case P -> isGamePaused = !isGamePaused;
Should we add a case for the ESC key? It would make it more intuitive to pause than pressing the P button I think

2023-01-07 20:48 UTC, sorinlzr commented on src/main/java/at/ac/fhcampuswien/snake/StateManager.java
> +public class StateManager {
Nice 👌

2023-01-07 20:48 UTC, sorinlzr commented on src/main/java/at/ac/fhcampuswien/snake/util/StateManager.java
> + * This class is responsible for switching between the different views and managing the gameBoard state.
Very good idea! 👌 👌

2023-01-07 20:48 UTC, sorinlzr commented on src/main/resources/at/ac/fhcampuswien/snake/main-view.fxml
> -                <MenuItem text="Exit" onAction="#onExitButtonClick"/>
Why did you remove the Exit menu option?

2023-01-07 22:13 UTC, benniii1 commented on src/main/java/at/ac/fhcampuswien/snake/controller/GameboardViewController.java
> +        this.gameBoard.setHeight(SCREEN_SIZE_MEDIUM - 50);
Done

2023-01-08 12:58 UTC, sorinlzr commented on src/main/java/at/ac/fhcampuswien/snake/controller/GameboardViewController.java
> +        this.gameBoard.setHeight(SCREEN_SIZE_MEDIUM - 50);
Did you delete the '- 50', is it not needed anymore?

2023-01-08 13:46 UTC, benniii1 commented on src/main/java/at/ac/fhcampuswien/snake/controller/GameboardViewController.java
> +        this.gameBoard.setHeight(SCREEN_SIZE_MEDIUM - 50);
I created new APP_HEIGHT_MEDIUM and APP_WIDTH_MEDIUM which account for the space of the header and footer.

2023-01-08 13:46 UTC, benniii1 commented on src/main/java/at/ac/fhcampuswien/snake/GameBoard.java
> +                case P -> isGamePaused = !isGamePaused;
I would keep P and implement ESC for exit to start screen.

2023-01-08 13:49 UTC, benniii1 commented on src/main/resources/at/ac/fhcampuswien/snake/main-view.fxml
> -                <MenuItem text="Exit" onAction="#onExitButtonClick"/>
It's a redundant button. We don't need it in every header Menu, because the windows close button does the same thing. 

In my opinion we can keep the button at the start screen, because it makes sense visually and logically to have a leave and start button there. But it isn't necessary either.

2023-01-08 13:59 UTC, benniii1 commented on src/main/java/at/ac/fhcampuswien/snake/GameBoard.java
> +                case P -> isGamePaused = !isGamePaused;
I just implemented the ESC shortcut to leave the game.

2023-01-08 14:34 UTC, sorinlzr commented on src/main/java/at/ac/fhcampuswien/snake/GameBoard.java
> +                case P -> isGamePaused = !isGamePaused;
Alright, but I would add a confirmation dialog before exiting the game, to inform the user that if they quit, they will lose all points

2023-01-08 14:38 UTC, sorinlzr commented on src/main/resources/at/ac/fhcampuswien/snake/main-view.fxml
> -                <MenuItem text="Exit" onAction="#onExitButtonClick"/>
Yes, but think at most apps you use - you have a windows close button, but also in the File menu there is always an Exit option. 

I don't find it redundant because if you are in the middle of a game, you have to go back to the first screen and then you can exit the game, but when you have the Exit option in the menu there, you can exit directly (as in the comment above, I would also ask for confirmation)

2023-01-08 14:56 UTC, sorinlzr requested changes
If you could move the game instructions from [gameboard-view.fxml](https://github.com/sorinlzr/snake/pull/17/files#diff-96fad8ce6ebf22c888759e86ee3d653078350a447908c04036b20fa1f8287070) to the main-menu view that would be great, this would be the only change request I would suggest.

The other changes are optional for now, we can do them later in another ticket, but they would be a nice to have I think (talking about the Exit menu item and the confirmation dialog)

2023-01-08 14:56 UTC, sorinlzr commented on src/main/resources/at/ac/fhcampuswien/snake/gameboard-view.fxml
> +    </VBox>
To be honest, I would add these informations in the main-menu screen, to make it clear before starting the game what the keys are and I would remove it from here

2023-01-08 14:56 UTC, sorinlzr commented on src/main/java/at/ac/fhcampuswien/snake/GameBoard.java
> +                case ESCAPE -> {
I would add a confirmation dialog before exiting the game, to inform the user that if they quit, they will lose all points. If he clicks Ok, then he returns to the main menu, if he clicks Cancel, then the game resumes

2023-01-08 17:41 UTC, benniii1 commented on src/main/java/at/ac/fhcampuswien/snake/GameBoard.java
> +                case ESCAPE -> {
Done, I also added a Rectangle with the word "Paused!" on it onto a border wall, when the game is paused.

2023-01-08 17:54 UTC, benniii1 commented on src/main/resources/at/ac/fhcampuswien/snake/gameboard-view.fxml
> +    </VBox>
Done.

2023-01-08 19:15 UTC, sorinlzr approved these changes

2023-01-09 09:25 UTC, merged