Feature/game board
sorinlzr/snake pull request #4
Opened 2022-12-26 16:30 UTC by benniii1

Implementation of a game board which can manage objects and events as well as an abstract class which will be used to create gameboard objects.

2022-12-30 19:54 UTC, benniii1 commented on .idea/misc.xml
>    <component name="FrameworkDetectionExcludesConfiguration">
Done

2022-12-30 19:55 UTC, benniii1 commented on .idea/misc.xml
>    <component name="FrameworkDetectionExcludesConfiguration">
Also, isn't the .idea folder a user dependent folder in intellij and should be ignored as a whole?

2022-12-30 20:01 UTC, benniii1 commented on src/main/java/at/ac/fhcampuswien/snake/GameBoard.java
> +    public void Run() {
Done

2022-12-30 20:01 UTC, benniii1 commented on src/main/java/at/ac/fhcampuswien/snake/GameBoard.java
> +    public void Stop() {
Done

2022-12-30 20:06 UTC, benniii1 commented on src/main/java/at/ac/fhcampuswien/snake/GameBoard.java
> +    private List<BoardObject> boardObjects = new ArrayList<>();
I made the first 3 fields final. 

boardObjects will change throughout the game. Idk. about Snake yet.

2022-12-30 20:07 UTC, benniii1 commented on src/main/java/at/ac/fhcampuswien/snake/ingameobjects/BoardObject.java
> +enum Type {
Ok for me, but I "learnt" that it is inside/next to the class you use it. I just see it always that way. But tbh I don't know whats the best practice on that

2022-12-31 08:37 UTC, benniii1 commented
@sorinlzr I amended the last three commits so that they have ticket information inside of their message. Also, they needed a merge from gameBoard into gameBoard afterwards. So now it looks like I did the same changes twice in history but the messages are okay now.

2022-12-31 08:52 UTC, benniii1 commented
@sorinlzr now the history is fine. Also it includes ticket names.

2022-12-31 16:14 UTC, sorinlzr commented on .idea/misc.xml
>    <component name="FrameworkDetectionExcludesConfiguration">
According to [this article](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems) on the JetBrains website and [the official JetBrains gitignore](https://github.com/github/gitignore/blob/main/Global/JetBrains.gitignore), some of the files in the .idea folder need to be shared.

2022-12-31 16:27 UTC, sorinlzr commented on src/main/java/at/ac/fhcampuswien/snake/GameBoard.java
> +    private List<BoardObject> boardObjects = new ArrayList<>();
A `List` can be final and you can still do changes to its content. If a `List` is final it means that you cannot change the reference to another place in memory, it will always point to the same `ArrayList` to which it was instantiated

2022-12-31 16:30 UTC, sorinlzr commented on src/main/java/at/ac/fhcampuswien/snake/ingameobjects/BoardObject.java
> +enum Type {
I think it's ok either way. I was more concerned about the name `Type`, that it wouldn't be clear enough

2022-12-31 16:31 UTC, sorinlzr approved these changes

2023-01-01 13:11 UTC, sorinlzr requested changes

2023-01-01 13:11 UTC, sorinlzr commented on .idea/.gitignore
> +.idea/misc.xml
can you move these `.xml` files in the main `.gitignore` please and also make sure to remove them from the git index ?
```
git rm .idea/misc.xml --cached
git add -u .idea/misc.xml
```

2023-01-01 15:24 UTC, benniii1 commented on .idea/.gitignore
> +.idea/misc.xml
@sorinlzr Done

2023-01-01 17:14 UTC, sorinlzr commented on .idea/.gitignore
> +.idea/misc.xml
@benniii1 I meant in the `.gitignore` in the repository root not the one in the `.idea` folder

2023-01-04 19:48 UTC, closed without merging

2023-01-04 19:49 UTC, sorinlzr commented
This merge request had multiple commits pertaining to 3 features. @benniii1 and I created 3 branches and created separate pull requests, which were previously merged.